import automaton

test1 = automaton.Automaton("test")
test1.add_transition("1", "a", "1")
test1.add_transition("1", "a", "2")
test1.add_transition("1", "b", "3")
test1.add_transition("2", "b", "3")
test1.add_transition("2", "%", "3")
test1.add_transition("2", "%", "4")
test1.add_transition("2", "a", "4")
test1.add_transition("4", "%", "5")
test1.add_transition("4", "b", "5")
test1.add_transition("3", "a", "5")
test1.add_transition("5", "a", "5")
test1.add_transition("5", "b", "2")
test1.add_transition("4", "a", "6")
test1.add_transition("5", "%", "6")
test1.add_transition("5", "a", "6")
test1.add_transition("6", "b", "6")
test1.make_accept("6")
test1.to_graphviz("test1.gv")
